### PR TITLE
Bucket by date

### PR DESCRIPTION
**Pull request by snikch**
I'm late

### CODE REVIEW

**Comment by snikch** [comment]
@mattevans What do you think are the requirements for timezones here? Do you want to pass in a location `Pacific/Auckland` for example, and all dates are changed to that timezone before bucketing?

**Comment by mattevans** [comment]
@snikch Yeah, I think it would be worthwhile. TZ's haven't been much of an issue up until now. This is a good solution. User TZ currently sits on the entity they fall into, so can easily pass through.

**Comment by snikch** [comment]
Ok, this is working with timezones I believe. Care for an eyes over?

**Comment by mattevans** [comment]
@snikch Woo! Had a quick look, LGTM. I'll test it out properly tomorrow AM. 👍

**Comment by mattevans** [comment]
Had a play this morning and got it going nicely with what I have so far!

Just added a quick `nil` check during `aggregate()` for empty cells (as the [last PR](https://github.com/snikch/aggro/pull/1) allowed `nil` values to be processed by `addRows()`).

**Review by mattevans — APPROVED** [review]

**Comment by snikch** [comment]
Sweet, I removed that in the merge conflict thinking that it'd be handled by the type statement. You could perhaps have put it in there instead but it's all good where it is too.

**Pull request merged**
